resources:
- name: ecr
  icon: AWS
  type: docker-image
  source:
    aws_access_key_id: ((aws-token))
    aws_secret_access_key: ((aws-secret))
    repository: ((aws-repo))

- name: project-release
  type: github-release
  source: 
    owner: ((github-username))
    repository: https://github.com/GevorgTonoyan/jokes-api.git
    access_token: ((github-access-token))
    release: true
    pre_release: true

- name: git-repo
  icon: github
  type: git
  source:
    uri: https://github.com/GevorgTonoyan/jokes-api.git
    branch: run-app
    username: ((github-username))
    password: ((github-access-token))


jobs:
- name: build-and-push
  plan:
  - get: git-repo
    trigger: true 
  - task: build
    file: git-repo/infra/ci/tasks/build-api.yml
    privileged: true
  - put: ecr-docker-reg
    params:
      build: ./git-repo
      tag_file: ./project-release/tag

# - name: pull-and-run
#   plan:
#   - get: ecr
#     trigger: true
#   - task: run-api
#     file: git-repo/infra/ci/tasks/run-api.yml
#     privileged: true



