resources:
- name: ecr
  type: docker-image
  source:
    aws_access_key_id: ((aws-token))
    aws_secret_access_key: ((aws-secret))
    repository: ((aws-repo))

- name: git-repo
  type: git
  source:
    uri: https://github.com/GevorgTonoyan/jokes-api.git
    branch: master
    username: ((github-username))
    password: ((github-access-token))

jobs:
- name: release-and-deploy
  plan:
  - get: git-repo
    trigger: true
  - put: ecr
    params:
      build: ./git-repo/api/
      tag: latest

# - name: run-api
#   plan: 
#     passed: 
#     - build-and-push
#     - get: git-repo
#       trigger: true
#     - task: run-flask
#       privileged: true
#       file: git-repo/infra/ci/tasks/run-api.yml
