resources:
- name: source
  type: git
  icon: github
  source:
    uri: https://github.com/GevorgTonoyan/jokesapi
    branch: develop
    
- name: image
  type: docker-image
  source:
    username: ((dockerhub_user))
    password: ((dockerhub_password))
    tag: latest
    repository: ((image-repo-name))/gevi

jobs:
- name: build-and-push
  plan: 
    - get: source
      trigger: true
    - task: build-image
      privileged: true
      file: source/infra/ci/tasks/buildapi.yml
      params:
        CONTEXT: concourse-examples/Dockerfiles/simple
    - put: image
      params:
        image: image/image.tar




