---
platform: linux

inputs:
  - name: git-repo
    path: .
    
image_resource: 
  type: docker-image
  source: 
    repository: vito/oci-build-task


outputs:
  - name: jokesapi

params:
  CONTEXT:
  DOCKERFILE:

run:
  path: build
                