---
platform: linux

image_resource: 
  type: docker-image
  source: 
    repository: vito/oci-build-task

inputs:
  - name: source

outputs:
  - name: image


params:
  CONTEXT: source/api/Dockerfile
      
run:
  path: build
