---
platform: linux

image_resource: 
  type: docker-image
  source: 
    repository: vito/oci-build-task

inputs:
  - name: source
    path: ./api

outputs:
  - name: jokesapi


params:
  CONTEXT:
  DOCKERFILE:
      
run:
  path: build
