---
platform: linux

image_resource: 
  type: docker-image
  source: 
    repository: vito/oci-build-task

inputs:
  - name: source

outputs:
  - gevi: jokesapi


params:
  CONTEXT: jokes-api
      
run:
  path: build
